version: '3'

services:

  dex-app: 
    container_name: dex-app
    image: dex-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/Dex?schema=public"
    ports:
      - '3000:3000'
    depends_on:
      - dex-db

  dex-db:
    container_name: dex-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Dex
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
