name: Docker Compose CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create .env
      run: cp .env.example .env
    - name: Build docker images
      run: docker-compose build
    - name: Run docker images
      run: docker-compose up -d
    - name: Clean up
      if: success() || failure()
      run: docker-compose down --rmi all -v --remove-orphans